# potli.us -> forwards to www.potli.us (both handled here)
server {
    listen       80;
    server_name  potli.us;

    return 301 https://www.potli.us$request_uri;
}

server {
    listen       80;
    server_name  www.potli.us;

    root  /usr/share/angie/html/potli.us;
    index index.html;

    access_log /var/log/angie/potli.us.access.log main;

    location / {
        try_files $uri $uri/ =404;
    }

    error_page 404 /404.html;
    location = /404.html {
        root /usr/share/angie/html/potli.us;
    }

    error_page 500 502 503 504 /50x.html;
    location = /50x.html {
        root /usr/share/angie/html;
    }
}